# Establecer la imagen base
FROM apache/spark

# Agregar el driver de PostgreSQL y guardarlo en la carpeta jars
RUN wget https://jdbc.postgresql.org/download/postgresql-42.6.0.jar -P /opt/spark/jars

